### PR TITLE
Support 2.12

### LINKED ISSUE #99: Publish 1.2.3 for scala 2.12
I see sttp is being upgraded, I guess that's also in the release of 1.2.3 right? Would be great to have it, still on 2.12 for a bit

### PR DESCRIPTION
**Pull request by Fristi**
Resolves #99 , but you have to publish with `sbt +publish` orsomething :)

### CODE REVIEW

**Comment by StuartJ45** [comment]
Thanks for this!
We noticed that using 2.13.1 over 2.13.0 breaks codecov for some reason, causing the circleci build to fail. We might have to leave it at 2.13.0 for now.

As for the 2.12 build, the sttp-akka-monix dependancy will need to be set to 1.0.1 when compiling with 2.12

**Comment by Fristi** [comment]
> As for the 2.12 build, the sttp-akka-monix dependancy will need to be set to 1.0.1 when compiling with 2.12

I saw some errors in the logs about that, but I don't get it :) Your dependencies are defined within the project right? So testing a master/PR version should not depend on published dependencies right?

**Comment by Fristi** [comment]
Everything is fixed now!

**Comment by Fristi** [comment]
Ready for merge and release? :D

**Comment by StuartJ45** [comment]
> Ready for merge and release? :D 
@Executioner1939

**Pull request merged**
